define({root:
({	
	"advisory_title": "Advisory Council",
	
	"advisory_para1" : "Austin Chiropractor Dr. Blessing Anyatonwu founded <a href= \"www.earnestholistichealth.com\">Earnest Holistic Health</a> to provide busy professionals with preventative chiropractic and nutritional care.  She knows first-hand the side effects of drugs, the toll that it can take on the body and the effect it has on the quality of life.  She is a graduate of the University of Bridgeport College of Chiropractic as well as the University of Bridgeport Nutrition Institute.  She completed an internship at the VA Connecticut Health Care System in Newington and West Haven, where she worked in an integrated, multi-disciplinary setting to provide care for our veterans.  She is certified by the National Board of Chiropractic Examiners and licensed by the state of Texas.  Dr. Blessing also has a Master&#8217;s in Human Nutrition.<br/><br/>Blessing believes that good nutrition plays a vital role in mental health and educates clients about the benefits of a diet rich in nutrients and lifestyle changes that can promote a good brain and overall health.  Clients going through the recovery process may have nutrient depletions caused by diet or medications.  With this in mind, Blessing facilitates a healthy overall nutritional regimen. <br/><br/> More details about Blessing can be found on <a href=\"www.linkedin.com/in/drblessinganyatonwu\">LinkedIn</a> and he can be reached by <a href=\"mailto:blessing@earnestholistichealth.com\">email<a/>. ",
	
	"advisory_para2" : "Veterinarian Dr. Brad Singleton is a graduate of Louisiana State University where he earned his Bachelor's degree and then attended the LSU School of Veterinary Medicine to earn his doctorate. During veterinary school, he was an active member in many organizations.  He served as president for Wildlife, Avian, Zoo, and Exotic Medicine, and was a Senior Co-Chair for the Raptor and Wildlife Rehabilitation Unit.  He was author and co-author of multiple research articles included in major peer-reviewed publications and spent his free time volunteering at a nature center.  One of his most rewarding experiences was volunteering to assist pets that were victims of Hurricane Katrina and their owners.  Brad founded <a href=\"www.southparkaustin.com\">South Park Animal Hospital</a> located in South Austin.<br/><br/>Brad is a staunch advocate within numerous areas of mental health and has seen with his own eyes the effect that animal ownership can have on anyone, especially those with mental health issues.  He routinely assists those that cannot afford traditional veterinary fees and contributes his time and professional skills to Clients of Beyond Today.<br/><br/>More details about Blessing can be found on <a href=\"www.linkedin.com/pub/charles-bradley-singleton/1a/518/5ab\">LinkedIn</a> and he can be reached by <a href=\"mailto:cbsingletondvm@gmail.com\">email<a/>.",
	
	"advisory_para3" : "Debbie Trammell serves as the Assistant Community Relations person and Volunteer Coordinator at <a href=\"www.dshs.state.tx.us/mhhospitals/austinsh/default.shtm\">Austin State Hospital</a>.  Debbie ensures that all proper procedures take place within this State agency from a Community Relations perspective and is one of the most positive and well-respected persons on the ASH campus.  She is responsible for many of the world-class events that occur at the hospital and provides awareness and acceptance of mental health issues within the community.  Debbie also endears herself to the numerous volunteers that ASH supports &#8212; from students wanting to be clinicians to consumers that want to be peers.<br/><br/>Debbie is also a &#8220;go to&#8221; person should one ever need assistance.  After decades of serving the hospital, she is familiar with the ins and outs and can always be counted upon.  She is a strong supporter of mental health issues in general and supports Beyond Today&#8217;s efforts in Peer Support, Recovery, Education and Informing Policy.<br/><br/> More details about Ruslyn can be found on <a href=\"www.linkedin.com/pub/deborah-trammell/7/a88/96a\">LinkedIn</a> and he can be reached by <a href=\"mailto:Debbie.Trammell@dshs.state.tx.us\">email<a/>.  ",
	
	"advisory_para4" : "Ruslyn Smith holds a license in clinical social work which reflects her commitment to social justice and a firm belief in every person&#8217;s inherent ability to heal, grow, and live a life that is most congruent with who she or he is as a person.   She sees counseling as a collaborative relationship to help people connect to, integrate and express the answers and solutions that exist within themselves toward a greater lived experience of well-being.  Ruslyn is the Executive Director of <a href=\"camhc.org\">Capital Area Counseling </a>.<br/><br/>Capital Area Counseling&#8217;s multi-disciplinary training and counseling center provides affordable, accessible, high quality services for the well-being of all Central Texans who desire them.  Income-based fees range from $10 - $50 per session and the length of service is determined only on the needs of the client.  We offer services to address virtually all mental health issues for individuals, couples and families.  Group therapy sessions are also available.  We believe in a philosophy that tailors therapy to each person&#8217;s unique individuality therefore our therapists practice from a wide range of approaches, including Cognitive Behavioral Therapy and other research supported ways to help reduce symptoms related to anxiety, depression, stress, and trauma.<br/><br/>More details about Ruslyn can be found on <a href=\"www.linkedin.com/pub/ruslyn-smith/8/a5a/a\">LinkedIn</a> and he can be reached by <a href=\"mailto:ruslyn@capitalareacounseling.org\">email<a/>. "

	})
});