define({
	root:({	
		"CriminalJusticePilot_Heading": "Criminal Justice Pilot",
		"CriminalJusticePilot_Para1": "Beyond Today's participation in re-entry panels and involvement on the Bureau of Justice Administration's Grant Advisory Board have led to increased efforts towards finding solutions to the various issues that arise at the crossroads of mental health and criminal recidivism.  We have convened a variety of leaders in both fields to consult on this issue, resulting in the formation of our first Criminal Justice Coalition.",
		"CriminalJusticePilot_Para2": "Durante el otoño de 2012, la Coalición trabajó para el diseño e implementación de un Piloto de Justicia Penal, que se inició en noviembre de 2012, en el Complejo Correccional del Condado de Travis ubicado en Del Valle. El objetivo del piloto es dar a los internos con problemas mentales apoyo de los compañeros mientras se encuentran en el interior del complejo, así como al salir del complejo. A la salida, más allá de hoy espera facilitar el proceso de reentrada y en última instancia reducir la reincidencia. Más allá de hoy facilitará:",
		"CriminalJusticePilot_Para3": "<li>Peer Support</li><li>Transportation</li><li>Housing</li><li>Food</li><li>Medicine</li><li>Physician</li><li>Psychiatry</li><li>Counseling</li><li>Eastern medicine</li><li>Acupuncture</li><li>Social and family networks</li><li>Faith</li><li>Education</li><li>Employment</li><li>Mobile phones</li><li>Psychotherapy</li><li>NutritionCounseling</li><li>Professional Life Coaching</li><li>Veterinary services</li>",
		"CriminalJusticePilot_Para4": "The pilot will last nine months.  The first three months will actively follow 50 individuals and the following six month will slowly decrease the amount of service while attempting to maintain contact with the individuals"
	}),
	"es": true
});