define(
({	
	"provider_title": "Proveedor Consejo",
	
	"provider_para" : "El Consejo de Proveedores de hoy M&#225;s all&#225; existe para mantener m&#225;s all&#225; de hoy al corriente personal y la junta de los nuevos avances en la prestaci&#243;n de servicios a los clientes que son relevantes para nuestro Sistema de Recuperaci&#243;n Orientada programa de Cuidado y cambiar mentalidades. Est&#225; compuesto por representantes de cada una de nuestras organizaciones asociadas.",
	
	"provider_para1" : "Ruslyn Smith tiene una licencia en trabajo social cl&#237;nico que refleja su compromiso con la justicia social y una firme creencia en la capacidad inherente de toda persona a sanar, crecer y vivir una vida que sea m&#225;s congruente con lo que ella o &#233;l es como persona. Ella ve consejer&#237;a como una relaci&#243;n de colaboraci&#243;n para ayudar a las personas conectarse, integrar y expresar las respuestas y soluciones que existen dentro de ellos mismos hacia una mayor experiencia vivida de bienestar. Ruslyn es el Director Ejecutivo de la Consejer&#237;a &#193;rea de la Capital.<br/><br/>Consejer&#237;a Capital Area multi-disciplinario formaci&#243;n y asesoramiento centro ofrece servicios asequibles, accesibles y de alta calidad para el bienestar de todos los tejanos centroamericanos que ellos desean. Basados ??en los ingresos las tasas oscilan entre $ 10 - $ 50 por sesi&#243;n y la duraci&#243;n del servicio se determina s&#243;lo en las necesidades del cliente. Ofrecemos servicios para hacer frente a pr&#225;cticamente todos los temas de salud mental para individuos, parejas y familias. Sesiones de terapia de grupo tambi&#233;n est&#225;n disponibles. Creemos en una filosof&#237;a que adapta la terapia a la individualidad &#250;nica de cada persona por lo tanto, nuestra pr&#225;ctica de los terapeutas de una amplia gama de enfoques, incluyendo la terapia cognitivo-conductual y otras formas de investigaci&#243;n apoyados para ayudar a reducir los s&#237;ntomas relacionados con la ansiedad, la depresi&#243;n, el estr&#233;s y trauma.<br/><br/>M&#225;s detalles sobre Ruslyn se puede encontrar en <a href=\"http://www.linkedin.com/pub/ruslyn-smith/8/a5a/a\" target=\"new tab\">LinkedIn</a> y se le puede contactar por correo <a href=\"mailto:ruslyn@capitalareacounseling.org\">electr&#243;nico</a>.",
	
	"provider_para2" : "Austin Chiropractor Dr. Blessing Anyatonwu fundada Salud Hol&#237;stica Earnest proporcionar a los profesionales ocupados con quiropr&#225;ctica de prevenci&#243;n y atenci&#243;n nutricional. Ella conoce de primera mano los efectos secundarios de los medicamentos, el peaje que puede llevar sobre el cuerpo y el efecto que tiene sobre la calidad de vida. Se gradu&#243; de la Universidad de Bridgeport College of Chiropractic, as&#237; como la Universidad de Bridgeport Nutrition Institute. Realiz&#243; una pasant&#237;a en el sistema de VA Connecticut Health Care en Newington y West Haven, donde trabaj&#243; en un enfoque integrado, multidisciplinario ajuste para atender a nuestros veteranos. Est&#225; certificada por la Junta Nacional de Examinadores de la Quiropr&#225;ctica y licenciado por el estado de Texas. Dr. Blessing tambi&#233;n tiene una Maestr&#237;a en Nutrici&#243;n Humana.<br/><br/>Bendici&#243;n cree que la buena nutrici&#243;n juega un papel vital en la salud mental y educa a los clientes acerca de los beneficios de una dieta rica en nutrientes y cambios de estilo de vida que pueden promover un buen cerebro y la salud en general. Los clientes que pasan por el proceso de recuperaci&#243;n puede tener el agotamiento de nutrientes causada por la dieta o medicamentos. Con esto en mente, Bendici&#243;n facilita un r&#233;gimen nutricional saludable en general.<br/><br/>M&#225;s detalles acerca de Blessing se puede encontrar en <a href=\"http://www.linkedin.com/in/drblessinganyatonwu\" target=\"new tab\">LinkedIn</a> y &#233;l puede ser alcanzado por correo <a href=\"mailto:blessing@earnestholistichealth.com\">electr&#243;nico</a>.",
	
	"provider_para3" : "El veterinario Dr. Brad Singleton es un graduado de la Universidad Estatal de Luisiana, donde obtuvo su licenciatura y luego asisti&#243; a la Escuela de Medicina Veterinaria de LSU para ganar su doctorado. Durante la escuela de veterinaria, fue un miembro activo de muchas organizaciones. Se desempe&#241;&#243; como presidente para la fauna, aviar, el zool&#243;gico y Medicina Ex&#243;tica, y estaba en el &#250;ltimo Co-Presidente de la Unidad de Rehabilitaci&#243;n Raptor y Vida Silvestre. Fue autor y co-autor de m&#250;ltiples art&#237;culos de investigaci&#243;n incluidos en publicaciones revisadas por pares principales y pasaba su tiempo libre como voluntaria en un centro de la naturaleza. Una de sus experiencias m&#225;s gratificantes como voluntaria para ayudar a las mascotas que fueron v&#237;ctimas del hurac&#225;n Katrina y sus propietarios. Brad fundada Sur Hospital Animal Park situado en el sur de Austin.<br/><br/>Brad es un firme defensor en numerosos &#225;mbitos de la salud mental y ha visto con sus propios ojos el efecto que la propiedad de los animales puede tener en cualquier persona, especialmente aquellos con problemas de salud mental. &#201;l rutinariamente ayuda a aquellos que no pueden pagar los honorarios veterinarios tradicionales y contribuye con su tiempo y sus capacidades profesionales a clientes de Beyond Today.<br/><br/>M&#225;s detalles acerca de Brad se pueden encontrar en <a href=\"http://www.linkedin.com/pub/charles-bradley-singleton/1a/518/5ab\" target=\"new tab\">LinkedIn</a> y &#233;l puede ser alcanzado por correo <a href=\"mailto:cbsingletondvm@gmail.com\">electr&#243;nico</a>."
	
	})
);